// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.Configuration;
using mystore.ecommerce.dbcontext.Models;

#nullable disable

namespace mystore.ecommerce.dbcontext
{
    public partial class EcommerceDbContext : DbContext
    {
        private readonly IConfiguration _config;
        public EcommerceDbContext(DbContextOptions<EcommerceDbContext> options, IConfiguration configuration)
         :base(options)
        {
            _config = configuration;
        }


        public  DbSet<Product> Products { get; set; }
        public  DbSet<Order> Orders { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder dbContextOptionsBuilder)
        {
            base.OnConfiguring(dbContextOptionsBuilder);
            dbContextOptionsBuilder.UseSqlServer(_config["ConnectionStrings:DefaultConnection"]);
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
        }
    }
}