// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.Configuration;
using mystore.ecommerce.dbcontext.Models;

#nullable disable

namespace mystore.ecommerce.dbcontext
{
    public class EcommerceDbContext : DbContext
    {
        public EcommerceDbContext()
        {

        }
        public EcommerceDbContext(DbContextOptions<EcommerceDbContext> options)
         :base(options)
        {
        }


        public  DbSet<Product> Products { get; set; }
        public  DbSet<Order> Orders { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder dbContextOptionsBuilder)
        {
            dbContextOptionsBuilder.UseSqlServer("Data Source=localhost\\SQLEXPRESS;Initial Catalog=EcommerceDB;Integrated Security=True;Connect Timeout=30;MultipleActiveResultSets=true");

            base.OnConfiguring(dbContextOptionsBuilder);   
            
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
        }
    }
}